### ISSUE TITLE
Adding back to top button[GSSoC'23]

### ISSUE THREAD

**Issue by Somya-Singhal** [aniketsinha2002/DataScienceWebsite.github.io#100]
Hi @aniketsinha2002 
I want to contribute to this project by adding a back-to-top button to take the user back to the top of the page if it will be clicked.
Please could you assign me this issue under GSSoC'23?
Thanks

**Comment by Gun2902** [comment]
can u assign me this issue

**Comment by Somya-Singhal** [comment]
@aniketsinha2002 Can you please label this issue as GSSoC'23?
