### ISSUE TITLE
In FAQ Section there is one question repeated 10 times with no proper answer

### ISSUE THREAD

**Issue by alivia-ansari** [aniketsinha2002/DataScienceWebsite.github.io#102]
I would like to change the content of the FAQ section. It should contain proper questions with proper answers to them. All the answers are Lorem Ipsum text. I want to contribute there. Could you assign this to me for GSSoC'23?

**Comment by raianiket010** [comment]
I can do it ... as I am a data science student I can suggest the best question I would feel happy if u would let me contribute
