### ISSUE TITLE
placing Social icon at appropriate place

### ISSUE THREAD

**Issue by GyanPrakashRaj** [aniketsinha2002/DataScienceWebsite.github.io#11]
DESKTOP VIEW
![icons](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/79048275/f4bddcaa-d58f-4ba8-82d7-d10f7f891d58)
MOBILE VIEW
![photo_2023-05-19_23-47-24](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/79048275/24bf0fe4-6253-4865-97b4-91609065cd20)

Hii Aniketsinha,
I have just visited this web Page✨. It seems it is in its initial phase.... I can improve some UI like shifting Social Icons at good position, Making a better UI for course section etc.🎨
These Changes/PRs will be considered in GSSOC23.
I request you to assign me this very First Issue.
THANK YOU 🤝

**Comment by shraddha761** [comment]
Hye 
I also visited website but their is no issue like this

**Comment by shraddha761** [comment]
Hye
I also visited website but their is no issue like this
![Screenshot 2023-05-19 234224](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/106100728/3d453ca1-1992-48a9-bc9c-138a41d139e4)
