### ISSUE TITLE
Social media icons

### ISSUE THREAD

**Issue by Anshkaran7** [aniketsinha2002/DataScienceWebsite.github.io#134]
The social media links in the footer section are not functioning properly. Can I add your social media links and implement a hover effect that will enhance the appearance of the site? Please assign me this issue under GSSOC 2023.
![Screenshot 2023-05-21 012610](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/106963118/1a9dfd36-90d0-4b70-9230-29abe9337855)

**Comment by masked-wolf18** [comment]
The social media links are not functioning properly. I can add your social media links. Please assign me this issue under GSSOC 2023.
