### ISSUE TITLE
make FAQ section visually appealing[GSSOC'23]

### ISSUE THREAD

**Issue by devanshibahuguna** [aniketsinha2002/DataScienceWebsite.github.io#136]
The FAQ section can be made to look better with vertical stacking and better design. Kindly assign me this issue under GSSoC'23

**Comment by purviporwal0** [comment]
I would love to work on this issue Pls assign this to me

**Comment by BTANISHA11** [comment]
I would like to work on this issue .
Can you pls assign this to me.
