### ISSUE TITLE
Add Favicon to the Website 

### ISSUE THREAD

**Issue by Sehaj-kahlon** [aniketsinha2002/DataScienceWebsite.github.io#152]
Adding a favicon that can appear next to the web page's title when open on the web or any other platform.
Please assign this issue to me under the GSSoC'23 label.

**Comment by masked-wolf18** [comment]
Please assign me this issue under GSSoC '23.

**Comment by Sehaj-kahlon** [comment]
@aniketsinha2002 can you label it to Gssoc'23.
And look into the pull request I made
