### ISSUE TITLE
Enable Smooth Scrolling Behavior (GSSOC'23)

### ISSUE THREAD

**Issue by vishnu9865** [aniketsinha2002/DataScienceWebsite.github.io#18]
The website navigates to the link's section abruptly and without smooth animation leading to poor UX, This can be solved via enabling Smooth Scrolling Behavior via CSS and disable it if the user's browser prefers reduced motion by using Media Query.

I would like to solve this issue. Please Assign this issue to me, Thank You.

**Comment by aniketsinha2002** [comment]
@vishnu9865 assigned!! Start working on the issue!!

**Comment by vishnu9865** [comment]
Thanks @aniketsinha2002 for assigning this project to me.
