### ISSUE TITLE
small bug in code

### ISSUE THREAD

**Issue by VaibhavTalkhande** [aniketsinha2002/DataScienceWebsite.github.io#184]
#describe issue:
there is closing script tag in index.html line 632 without opening
![Screenshot (43)](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/49303222/e40218e2-a6b3-4c90-9805-d867a94bafda)

**Comment by VaibhavTalkhande** [comment]
i want to fix it under Gssoc 23

**Comment by sumit851** [comment]
is this issue was closed or it is opened till now
