### ISSUE TITLE
Fix the image position in smaller screens 

### ISSUE THREAD

**Issue by rolikaagarwal** [aniketsinha2002/DataScienceWebsite.github.io#20]
The image of the Learn Data Science section is coinciding with the image of the What is data science section. I will make the second section (What is data science section)  more responsive across all screen sizes and fix the image problem. Assign me this issue.

![image](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/81984963/590a8995-3b0e-4a7d-bb0e-3ccbd13237c0)

![image](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/81984963/1e892dbf-b06c-4e98-bcc0-4891eb735d3d)

**Comment by rolikaagarwal** [comment]
Assign me this issue.

**Comment by aniketsinha2002** [comment]
@rolikaagarwal assigned!! Start working on the issue!!

**Comment by SimranLahrani842** [comment]
It appears correctly in desktop site though in mobile!!
