### ISSUE TITLE
[GSSoC'23] UI and mail link Improvement

### ISSUE THREAD

**Issue by yashpreet2707** [aniketsinha2002/DataScienceWebsite.github.io#208]
first image shows the current                    
and  the second one shows the suggested one.

suggested one has improved (professional looking) social links, and *anchor link with the mail given above them*
Please assign me this issue under GSSoC'23. Really looking forward to contribute to this project.

<img width="320" alt="prev" align="left" src="https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/111020648/76f606a9-769a-492a-8b89-38049e5c9664">
<img width="354" alt="now" align="right" src="https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/111020648/bb54fde8-b8ab-4747-999a-59e7e7dfae80">

**Comment by shubham725809** [comment]
I am a full-stack developer, so adding this feature is not a big task for me. so please assign me this and I am also a GSSOC 2023 contributor

**Comment by chiki012** [comment]
Hello, I'm good at front-end and have knowledge of CSS.  please assign me this issue.
I'm GSSOC'23 contributor.

**Comment by yashpreet2707** [comment]
it's been a long time, I'm closing the issue
