### ISSUE TITLE
`README` bold font not supported.

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [aniketsinha2002/DataScienceWebsite.github.io#267]
Hello,
Here is a issue regarding `README.md`

## Screenshot -
![Screenshot from 2023-05-23 01-51-05](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/121503426/b7aea64e-489a-47ef-a3e2-294d46559f4b)

## I will raised a **PR** for this very soon.

**Comment by SyedImtiyaz-1** [comment]
I'm just checking the `README.md` again and I just found, I more issue regarding the **bold font** in the last of the `README`
<hr>

## Screenshot - 
![Screenshot from 2023-05-23 02-02-23](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/121503426/d2d59ff0-e00b-4919-8e99-28b11c78946d)

**Comment by SyedImtiyaz-1** [comment]
## Check the PR for this issue here - #268

**Comment by Vickyaryan33** [comment]
@SyedImtiyaz-1 please assign me i would be contribute in Ggsoc 2023

**Comment by SyedImtiyaz-1** [comment]
@Vickyaryan33 I have already solved this.
### Check the PR #268
