### ISSUE TITLE
 add pages for courses 

### ISSUE THREAD

**Issue by shivaniyuvrajyadav** [aniketsinha2002/DataScienceWebsite.github.io#27]
we can add more detailed information about each course like career opportunity & modules that will cover in that particular course 
please assign me these.

**Comment by Manishak798** [comment]
I would like to contribute to this, and I will add pages to courses that make it more readable. Please assign me this issue under GSSOC.

**Comment by SimranLahrani842** [comment]
> I would like to contribute to this, and I will add pages to courses that make it more readable. Please assign me this issue under GSSOC.

I m also a contributor hence asking for issue

**Comment by shivaniyuvrajyadav** [comment]
Do I have to add content by myself or you will be providing it

**Comment by shivaniyuvrajyadav** [comment]
#280 add course page
