### ISSUE TITLE
Bug in the `Hero Page` 

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [aniketsinha2002/DataScienceWebsite.github.io#312]
Hello @aniketsinha2002,

Jumping on the points as I recovered many bug and add new features in the website so here is one more bug that I found.

## Screenshot - 
![Screenshot from 2023-05-24 12-46-42](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/121503426/4fdd8d65-2880-4292-af92-520c0218b482)

**Comment by manoranjanonline** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23
