### ISSUE TITLE
[bug] Sign-up button in navbar isnt properly sized

### ISSUE THREAD

**Issue by Ghat0tkach** [aniketsinha2002/DataScienceWebsite.github.io#33]
current behaviour
![image](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/59855919/658009ac-dd1d-4a0d-87ca-07d9802ba04e)

Expected behaviour
![image](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/59855919/007890b5-3cbe-4c3f-ac39-f8eb6eca7656)

and also icon is missing from website tab ,
i would like to work on this issue under gssoc 23

**Comment by yashpreet2707** [comment]
i've already done that, but i don't why PR is not made 
https://github.com/yashpreet2707/DataScienceWebsite.github.io/commit/79e8d23958daa749c5804f02e09b5fb6258e36a3

**Comment by Ghat0tkach** [comment]
> i've already done that, but i don't why PR is not made [yashpreet2707@79e8d23](https://github.com/yashpreet2707/DataScienceWebsite.github.io/commit/79e8d23958daa749c5804f02e09b5fb6258e36a3)

i dont whether you are familiar with open-source or not but you arent supposed to solve issues of others until assignment, you cant draft a PR directly for unassigned issues . It is against the spirit of open-source

**Comment by yashpreet2707** [comment]
Yeah mate, I am new to open source and am really sorry for what I did. I'll take care next time.

**Comment by Ghat0tkach** [comment]
> Yeah mate, I am new to open source and am really sorry for what I did. I'll take care next time.

no worries mate :3
