### ISSUE TITLE
Footer styles  [GSSoC'2023]

### ISSUE THREAD

**Issue by Kwamecody** [aniketsinha2002/DataScienceWebsite.github.io#37]
Hi there,

There are some things I will like to draw your attention to.

- The privacy section header of the footer is misspelled, it will also be helpful if all the links are working.
- The first section in the footer has a  dummy text, it will be beneficial if an actual text is used.
- All the social media profiles are not linked.

I will be very grateful if you could assign me this issue.
Thank you .

**Comment by bhavyanarnoli** [comment]
Hey @Kwamecody i woul like to work on this please assign it to me

**Comment by bhavyanarnoli** [comment]
or if we can do it together

**Comment by Aditi323** [comment]
I would like to work on this project. Please assign it to me.

**Comment by aniketsinha2002** [comment]
Guys, please keep in mind that I can only assign issues on a first-come, first-serve basis. If you find any issues that haven't been opened, please open an issue and start working on it.

If you can't, don't worry, I will also be opening up issues that need to be fixed by someone within a day or two. You'll be able to contribute to those as well. Stay active!

**Comment by Kwamecody** [comment]
> or if we can do it together

No problem.

**Comment by Kwamecody** [comment]
> Guys, please keep in mind that I can only assign issues on a first-come, first-serve basis. If you find any issues that haven't been opened, please open an is
> 
> If you can't, don't worry, I will also be opening up issues that need to be fixed by someone within a day or two. You'll be able to contribute to those as well. Stay active!

He

**Comment by Kwamecody** [comment]
Hello Sir,

Please could you send me  the URL to the social media handles.

Thank you in advance.
