### ISSUE TITLE
Adding favicon to the website

### ISSUE THREAD

**Issue by anuza08** [aniketsinha2002/DataScienceWebsite.github.io#39]
Favicon is missing in the website.

*I can solve this issue**

**Comment by Rajput-vinay** [comment]
I can solve easily this

**Comment by Srija-Burugula** [comment]
This website doesn't have a Favicon, I would like to work on it. Please assign this to me.

**Comment by vanshgoel18** [comment]
I can solve this issue plz assign this issue to me in GSSOC'23.
<img width="960" alt="Screenshot 2023-05-20 114444" src="https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/91386624/0ea91a5c-e48a-4138-a185-69527fdf38f4">

**Comment by PatilHarshh** [comment]
Wohh Excited @aniketsinha2002

**Comment by Silentshooter** [comment]
I want to work on this issue under GSSOC '23 . So please approve my request.
