### ISSUE TITLE
I want to add an email sending feature to the "Contact Us" .

### ISSUE THREAD

**Issue by mandliyarajendra11** [aniketsinha2002/DataScienceWebsite.github.io#46]
use a third-party email service provider/api.
Create a form on the "Contact Us" 

After that, when the user enters their message and email and clicks on the "Send Mail" button, the message will be received in your email.

can i work on this issue under gssoc 23

**Comment by aniketsinha2002** [comment]
@mandliyarajendra11  Assigned! Excited to see the changes you will make!! :octocat:
