### ISSUE TITLE
Add a smooth slide down transition to the FAQ accordion [GSSoc23]

### ISSUE THREAD

**Issue by ChinatuL** [aniketsinha2002/DataScienceWebsite.github.io#47]
Hello. I would like to add a slide-down transition to the accordion in the FAQ section. When it is clicked, the answer just pops up. I would like to fix this. Kindly assign this issue to me as a Gssoc contributor.

**Comment by Aditi323** [comment]
I would like to work on this project. Please assign it to me as a Gssoc contributor.

**Comment by ChinatuL** [comment]
> I would like to work on this project. Please assign it to me as a Gssoc contributor.

I am also a contributor and would love to fix the issue, that is why I opened it.

**Comment by ChinatuL** [comment]
Just noticed someone has already solved this issue.
