### ISSUE TITLE
Update the readme

### ISSUE THREAD

**Issue by sumitkr2000** [aniketsinha2002/DataScienceWebsite.github.io#51]
Hey @aniketsinha2002 I want to update the readme to add how to get started contributing and the steps for it. Also, I want to add a section for the contributor's list. Please assign me this issue. Thank you!

**Comment by Shrejal123** [comment]
Hello,@aniketsinha2002 I am interested to update the readme fille and wants to add some more information about Data Science. Could you please assign it to me ?

**Comment by aniketsinha2002** [comment]
@Shrejal123 If you want to add more information to the Readme about our website, Please open up a new issue with the proper title, then I can assign that to you!!

**Comment by Shrejal123** [comment]
@aniketsinha2002 I raised title(Enhance Website Information and content) of the issue please assigned to me.

**Comment by PriyankaTamhankar01** [comment]
Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project. Kindly provide me the opportunity to work on the issue. @aniketsinha2002
