### ISSUE TITLE
[Important] Flow Lost

### ISSUE THREAD

**Issue by crapbagaah** [aniketsinha2002/DataScienceWebsite.github.io#553]
### Description

The website has entirely lost its flow, I would like to work on fixing of the landing page so that I can make it a proper landing paper.  I'll fix everything on the landing paper including the header, alignment, and media query. I'll make it look exactly like how it was. Please assign this work to me under GSSOC'23. Thank you

### Screenshots

![image](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/90127903/a28a71a6-4a62-4b2f-aad9-683665684a97)

**Comment by aniketsinha2002** [comment]
@crapbagaah assigned !!

**Comment by crapbagaah** [comment]
@aniketsinha2002 thank you for assigning the issue, by when do you want me to complete the issue?

**Comment by aniketsinha2002** [comment]
Is it okay for you to complete it by tomorrow? @crapbagaah

**Comment by crapbagaah** [comment]
@aniketsinha2002 can I get a 2days time? I have assignments due today, tomorrow, and the day after tomorrow. Can I complete it by Monday if it's okay for you? Or else I'll try to do it by tomorrow

**Comment by aniketsinha2002** [comment]
@crapbagaah  Okay fine take your time and complete it by Monday!

**Comment by crapbagaah** [comment]
@aniketsinha2002 Yes definitely, thank you!

**Comment by crapbagaah** [comment]
@aniketsinha2002  I'm making changes in the css file but I cannot see the changes on the website, what can be the issue?

For reference, I changed the navbar background to red
![image](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/90127903/dc38744e-b95e-4ce9-9069-523410cd5ccd)



**But nothing is changing on the website**
![image](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/90127903/61daac59-3d97-49fb-ad14-a80e57e66103)

**Comment by aniketsinha2002** [comment]
The CSS file might not be linked to HTML file. Check that once!!

**Comment by crapbagaah** [comment]
it is there, I'm checking what is wrong with the files, I have worked on it on my laptop separately but the same is not working when I'm doing it on the main code

![image](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/90127903/064b51cb-a699-44a1-ba97-81ed1c84118c)

**Comment by crapbagaah** [comment]
@aniketsinha2002 I'm almost done but I need a bit more time to fix a few things. This is also my first-ever contribution, I hope you can consider and give me some more time

![image](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/90127903/aa1417cc-eb66-4558-8b7b-eea96658d9d0)
