### ISSUE TITLE
Add some effects in the achievement and popular course section

### ISSUE THREAD

**Issue by shruti8302** [aniketsinha2002/DataScienceWebsite.github.io#58]
Hey @aniketsinha2002 ,
As a part of GSSOC'23, I would like to improve the UI by adding some hovering effects on the achievement and popular course section. Kindly assign this issue to me.

**Comment by Srija-Burugula** [comment]
I want to improve the UI by adding a testimonial section. please assign this issue to me.

**Comment by shruti8302** [comment]
Hey @aniketsinha2002
Could u please label it as GSSOC'23?
