### ISSUE TITLE
nav bar issue and website totally broken 

### ISSUE THREAD

**Issue by Sushilverma002** [aniketsinha2002/DataScienceWebsite.github.io#580]
### Description

broken

### Screenshots

![image](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/114687502/9a9c4c8b-7bdf-43cd-9db2-ee77b48259bc)

![image](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/114687502/d2f7e84f-0639-4583-ac40-894cab8547b2)

![image](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/114687502/e817916f-1f35-4da7-874b-7413807c7145)

**Comment by aniketsinha2002** [comment]
@Sushilverma002 Assigned!!
