### ISSUE TITLE
[FEATURE] Improve the UI of the footer

### ISSUE THREAD

**Issue by sumitkr2000** [aniketsinha2002/DataScienceWebsite.github.io#586]
### Description

Hey @aniketsinha2002 I want to improve the UI of the footer. Currently, it is not styled and looks like very basic HTML. Please assign me this issue. Thank you!

### Screenshots

![image](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/100675296/1c739bd5-8e82-488d-a6bc-533a78e457f0)

**Comment by Manish12-verma** [comment]
please assign this issue to me
