### ISSUE TITLE
Navbar broken

### ISSUE THREAD

**Issue by DivyanshiNarang** [aniketsinha2002/DataScienceWebsite.github.io#609]
### Description

Sign-in button is not visible properly in the navbar.

@aniketsinha2002 Please assign this issue to me under gssoc'23.

### Screenshots

<img width="960" alt="Screenshot 2023-07-04 002056" src="https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/74779601/ef666eae-2ecf-4405-8f09-bc84bd48cdf5">

**Comment by Neha626177** [comment]
I would like work on this issue. please assign me this project.
Thank You.
