### ISSUE TITLE
[FEATURE] adding a contact us form

### ISSUE THREAD

**Issue by ePSA-eJya** [aniketsinha2002/DataScienceWebsite.github.io#636]
### Description

adding a contact us formin the contact page
 please assign this issue to me @aniketsinha2002 
i a m gssoc23 contributor

**Comment by sakshimaluskar2** [comment]
I want add contact us form in contact page.

Solution -
By incorporating a "Contact Us" form on a data science website, the website owner can foster engagement, encourage collaboration, gather valuable feedback, and establish connections with users, industry professionals, and potential clients or partners.

![datasc](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/128711718/ec5cd917-f107-4f21-93a4-102f49e969ab)

I will able to do the contact us form more attractive .
I am GSSoC'23 Contributor. please assign me this issue.

**Comment by sakshimaluskar2** [comment]
hey @aniketsinha2002  I will be able to do this ,please assign this issue to me.
