### ISSUE TITLE
Hovering is not working on email and contact us

### ISSUE THREAD

**Issue by KumariShaliniDwivedi** [aniketsinha2002/DataScienceWebsite.github.io#651]
### Description

When we hover over the gmail and contact number in the contact us section then it doesn't turn green and doesn't get underlined like the other options under Home, Primacy section

### Screenshots

Uploading Data Science Portal _ A complete resources to become a Data Scientist - Google Chrome 2023-07-15 21-42-45.mp4…

**Comment by Semako123** [comment]
Can I work on this

**Comment by KumariShaliniDwivedi** [comment]
Actually I want to work on this under gssoc 2023

**Comment by Semako123** [comment]
Okay

**Comment by AshitaBidkar** [comment]
I want to work on this issue, kindly assign it to me.
