### ISSUE TITLE
To added a hover effect in footer socials

### ISSUE THREAD

**Issue by Arjundotadex** [aniketsinha2002/DataScienceWebsite.github.io#675]
### Description

The footer social section of the index page is having a simple hover effect. 
A new hover effect can be added to make it look more clean.

### Screenshots

![image](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/103199408/423760ee-ace6-45ec-a8f9-3d1918dffa55)

**Comment by Harshsaini001** [comment]
I want to add add hover effects in footer icons. Please assign this issue to me
