### ISSUE TITLE
there is no margin between cards

### ISSUE THREAD

**Issue by charu1603** [aniketsinha2002/DataScienceWebsite.github.io#685]
### Description

giving margin to these cards will improve the UI
![Screenshot (356)](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/96014425/fff2abe6-312a-423e-8417-3e6d51b86dd6)

**Comment by karandeep4423** [comment]
can anybody assign this issue?

**Comment by Ganaik2004** [comment]
@charu1603 I want to work on this issue please assign it to me.

**Comment by charu1603** [comment]
@Ganaik2004 I raised the issue so that you can assign it to me , but I didn't get any response from you 🥲

**Comment by aniketsinha2002** [comment]
@Ganaik2004 It's been more than 3 days and the work isn't done yet! Cant give more time! 

@charu1603 Assigned!
