### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by hackkbee** [aniketsinha2002/DataScienceWebsite.github.io#712]
### Description

The content below the footer should be removed.
<img width="959" alt="image" src="https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/92021777/f435de43-597a-4eb0-9fb7-881968623151">

**Comment by Ganaik2004** [comment]
I WNT TO WORK ON THIS ISSUE CAN YOU PLEASE ASSIGN IT TO ME.

**Comment by Ganaik2004** [comment]
Footer is already been fix .
