### ISSUE TITLE
Contact us page is not proper for mobile screens also we are not able to navigate to other pages while being on contact us page

### ISSUE THREAD

**Issue by ratishjain12** [aniketsinha2002/DataScienceWebsite.github.io#718]
### Description

Please assign me this issue and I'll fix it 

@aniketsinha2002 

### Screenshots

in the below ss you can see that Contact page heading is pushed down lot making it go out of visibility for mobile users 

![Screenshot 2023-08-05 015703](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/43003421/fb11cf66-2577-4f8a-891c-92106b5a7e65)

also there is navigation drawer while resizing as well as we cant navigate from this page

**Comment by aniketsinha2002** [comment]
@ratishjain12 Go for it!!
