### ISSUE TITLE
Issue: Scroll Animation Offset Causes Inaccurate Jump

### ISSUE THREAD

**Issue by tamannaaaaa** [aniketsinha2002/DataScienceWebsite.github.io#722]
### Description

The current scroll animation in the provided code snippet has an offset of -140 pixels from the top of the target section. While the intention behind adding the offset might be to account for a fixed header, it introduces an issue where the scrolling behavior becomes inaccurate under certain circumstances.

**Comment by tamannaaaaa** [comment]
Please assign this issue to me so I could fix it

**Comment by tamannaaaaa** [comment]
While pushing, it's showing that I don't have access to this file. The url returns error 403

**Comment by aniketsinha2002** [comment]
@tamannaaaaa Hey Tamanna, error 403 suggests a permissions problem, but if others are pushing without problems, it could be related to your account settings or local configuration. You should once double-check your credentials, repository URL, and authentication method to ensure everything is set up correctly on your end.

**Comment by tamannaaaaa** [comment]
@aniketsinha2002 I have solved this issue and created a PR. Please check it out.
