### ISSUE TITLE
[FEATURE] want to add footer at contact section 

### ISSUE THREAD

**Issue by Sushilverma002** [aniketsinha2002/DataScienceWebsite.github.io#732]
### Description

want to add footer at contact section 

### Screenshots

![image](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/114687502/9c8a95b8-3ab4-41e1-baae-cd898d8590df)

**Comment by Neha626177** [comment]
Please assign me this issue I would like to solve this issue.
